<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- External fonts -->
        <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto:400,500" rel="stylesheet">

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/offcanvas.min.css'))
            ->prependStylesheet($this->basePath('css/owl.theme.default.min.css'))    
            ->prependStylesheet($this->basePath('css/owl.carousel.css'))
            ->prependStylesheet($this->basePath('fonts/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/itechmedia.js'))
            ->prependFile($this->basePath('js/offcanvas.min.js'))
            ->prependFile($this->basePath('js/script.js'))
            ->prependFile($this->basePath('js/owl.carousel.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <div id="main-wrapper">
            <!-- Header Section -->
            <header>
                <div class="container">
                    <div class="top_ber">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="top_ber_left">
                                    20 August. Thursday 2015. 2:00 PM.
                                </div><!--top_ber_left-->
                            </div><!--col-md-6-->
                            <div class="col-md-6">
                                <div class="top_ber_right">
                                    <div class="top-menu">
                                        <ul class="nav navbar-nav">    
                                            <li><a href="#">Login</a></li>
                                            <li><a href="#">Register</a></li>
                                        </ul>
                                    </div><!--top-menu-->
                                </div><!--top_ber_left-->
                            </div><!--col-md-6-->
                        </div><!--row-->
                    </div><!--top_ber-->

                    <div class="header-section">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="logo">
                                <a  href="index.html"><img class="img-responsive" src="img/logo.png" alt=""></a>
                                </div><!--logo-->
                            </div><!--col-md-3-->

                            <div class="col-md-6">
                                <div class="header_ad_banner">
                                <a  href="#"><img class="img-responsive" src="img/img_ad.jpg" alt=""></a>
                                </div>
                            </div><!--col-md-6-->

                            <div class="col-md-3">
                                <div class="social_icon1">
                                        <a class="icons-sm fb-ic"><i class="fa fa-facebook"></i></a>
                                        <!--Twitter-->
                                        <a class="icons-sm tw-ic"><i class="fa fa-twitter"></i></a>
                                        <!--Google +-->
                                        <a class="icons-sm gplus-ic"><i class="fa fa-google-plus"> </i></a>
                                        <!--Linkedin-->
                                        <a class="icons-sm li-ic"><i class="fa fa-linkedin"> </i></a> 
                                        <!--Pinterest-->
                                        <a class="icons-sm pin-ic"><i class="fa fa-pinterest"> </i></a>
                                </div> <!--social_icon1-->
                            </div><!--col-md-3-->
                        </div> <!--row-->	
                    </div><!--header-section-->    	      
                </div><!-- /.container -->   

                <nav class="navbar main-menu navbar-inverse navbar-static-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed pull-left" data-toggle="offcanvas">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        </div>
                        <div id="navbar" class="collapse navbar-collapse sidebar-offcanvas">
                        <ul class="nav navbar-nav">
                            <li class="hidden"><a href="#page-top"></a></li>
                            <li><a class="page-scroll" href="category.html">Baseball</a></li>
                            <li><a class="page-scroll" href="category.html">Football</a></li>
                            <li><a class="page-scroll" href="category.html">Hockey</a></li>
                            <li><a class="page-scroll" href="category.html">Basketball</a></li>
                            <li><a class="page-scroll" href="category.html">Boxing</a></li>
                            <li><a class="page-scroll" href="category.html">Golf</a></li>
                            <li><a class="page-scroll" href="category.html">Tennis</a></li>
                            <li><a class="page-scroll" href="category.html">Horse racing</a></li>
                            <li><a class="page-scroll" href="category.html">Track & Field</a></li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="pull-right">
                            <form class="navbar-form" role="search">
                                <div class="input-group">
                                    <input class="form-control" placeholder="Search" name="q" type="text">
                                    <div class="input-group-btn">
                                        <button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        </div>
                    </div>
                </nav> 
                <!-- .navbar -->
            </header>
            <?= $this->content ?>
            <hr>
            <!-- Footer Section -->
            <footer class="footer_section section_wrapper section_wrapper" >
                <div class="footer_top_section">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="text_widget footer_widget">
                                <div class="footer_widget_title"><h2>About Sports Mag</h2></div>

                                <div class="footer_widget_content">Collaborativelyadministrate empowered marketsplug-and-play networks. Dynamic procrastinate after.marketsplug-and-play networks. Dynamic procrastinate users after. Dynamic procrastinateafter. marketsplug-and-play networks. Dynamic procrastinate users after...
                                </div>
                                </div><!--text_widget-->
                            </div><!--col-xs-3-->

                            <div class="col-md-6">
                                <div class="footer_widget">
                                    <div class="footer_widget_title"><h2>Discover</h2></div>
                                    <div class="footer_menu_item ">
                                    <div class="row">
                                        <div class="col-sm-4"> 
                                            <ul class="nav navbar-nav ">
                                                <li><a href="../navbar/">Baseball</a></li>
                                                <li><a href="../navbar-static-top/">Football</a></li>
                                                <li><a href="./">Cricket</a></li>
                                                <li><a href="../navbar/">Rugbi</a></li>
                                                <li><a href="../navbar/">Hockey</a></li>
                                                <li><a href="../navbar-static-top/">Boxing</a></li>
                                                <li><a href="./">Golf</a></li>
                                                <li><a href="../navbar/">Tennis</a></li>
                                                <li><a href="../navbar/">Horse Racing</a></li>
                                            </ul>
                                        </div><!--col-sm-4-->
                                        <div class="col-sm-4 "> 					  						
                                            <ul class="nav navbar-nav  ">
                                                <li><a href="../navbar/">Track & Field</a></li>
                                                <li><a href="../navbar-static-top/">MembershipContact us</a></li>
                                                <li><a href="./">Newsletter Alerts</a></li>
                                                <li><a href="../navbar/">Podcast</a></li>
                                                <li><a href="../navbar/">Blog</a></li>
                                                <li><a href="../navbar-static-top/">SMS Subscription</a></li>
                                                <li><a href="./">Advertisement Policy</a></li>
                                                <li><a href="../navbar/">Jobs</a></li>
                                            </ul>
                                        </div><!--col-sm-4-->
                                        <div class="col-sm-4"> 
                                            <ul class="nav navbar-nav ">
                                                <li><a href="../navbar/">Report technical issue</a></li>
                                                <li><a href="../navbar-static-top/">Complaints & Corrections</a></li>
                                                <li><a href="./">Terms & Conditions</a></li>
                                                <li><a href="../navbar-static-top/">Privacy Policy</a></li>
                                                <li><a href="./">Cookie Policy</a></li>
                                                <li><a href="../navbar/">Securedrop</a></li>
                                                <li><a href="../navbar/">Archives</a></li>
                                            </ul>
                                        </div><!--col-sm-4-->
                                    </div><!--row-->
                                </div><!--footer_menu_item-->
                                </div><!--footer_widget-->
                            </div><!--col-xs-6-->

                            <div class="col-md-3">
                                <div class="text_widget footer_widget">
                                    <div class="footer_widget_title"><h2>Editor’s Message</h2></div>
                                    <img src="img/img-author.jpg" />
                                    <div class="footer_widget_content">Collaborativelyadministrate empowered marketsplug-and-play networks. Dynamic procrastinate after.marketsplug-and-play networks. Dynamic procrastinate users after. Dynamic procrastinateafter. marketsplug-and-play networks. Dynamic procrastinate users after...</div>
                                </div>
                            </div><!--col-xs-3-->
                        </div><!--row-->
                    </div><!--container-->
                </div><!--footer_top_section-->
                <a href="#" class="crunchify-top"><i class="fa fa-angle-up" aria-hidden="true"></i></a>

                <div class="copyright-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3">
                                    Editor: Joshep guinter Grunt
                            </div><!--col-xs-3-->
                            <div class="col-md-6">
                                <div class="copyright">
                                © Copyright 2015 - Sports News Mag.com. Design by: <a href="https://uiCookies.com" title="uiCookies">uiCookies</a>
                                </div>
                            </div><!--col-xs-6-->
                            <div class="col-md-3">
                                Sports News Magazine
                            </div><!--col-xs-3-->
                        </div><!--row-->
                    </div><!--container-->
                </div><!--copyright-section-->
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
