<div class="media">
    <div class="media-left">
        <a href="#"><img class="media-object" src="<?= $image ?>" alt="Generic placeholder image"></a>
    </div><!--media-left-->
    <div class="media-body">
        <h4 class="media-heading"><a href="<?= $url ?>"><?= $text ?></a></h4>
        <span class="rating text-muted"><?= $timeElapsed ?></span>
    </div><!--media-body-->
</div><!--media-->